name: Build Python Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Укажите нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Установите pyinstaller
        pip install -r requirements.txt  # Установите зависимости вашего проекта

    - name: Build executable
      run: |
        pyinstaller --onefile main.py

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag: v1.0.0  # Укажите версию релиза
        files: dist/main.exe  # Замените на имя вашего исполняемого файла
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
